name: polymer_elements
author: Vittorio Ballestra <vittorio.ballestra@gmail.com>
homepage: https://github.com/dam0vm3nt
description: Polymer-2 support for Dart

version: 2.0.0-preview.1
dependencies:
  polymer_element: any
  js: any
  html5: ^0.0.3
dependency_overrides:
  polymer_element:
   path: ../polymer_element
